# AI Seminar - Part 2 - Practical Test (July 2023)

**Συμπληρώστε παρακάτω τα στοιχεία σας:**

**Επώνυμο:         **

**Όνομα:           **

**Σχολή:           **

**Α.Μ.:            **



### Ζητούμενα - Οδηγίες
Καλείστε να υλοποιήσετε δύο διαφορετικές αρχιτεκτονικές νευρωνικών δικτύων για να επιλύσετε το πρόβλημα της ταξινόμησης εικόνων σε κλάσεις. Το dataset στο οποίο θα εργαστείτε είναι το **CIFAR-10**. Μπορείτε να βρείτε πληροφορίες και να κατεβάσετε το CIFAR-10 [εδώ](https://www.cs.toronto.edu/~kriz/cifar.html).

Θα πρέπει να υλοποιήσετε δύο αρχιτεκτονικές για την **ταξινόμηση των εικόνων σε 10 κλάσεις**:

(1) Ένα **συνελικτικό νευρωνικό δίκτυο (Convolutional Neural Network - CNN)**.

(2) Ένα **πολυστρωματικό perceptron (MLP) 5 επιπέδων (4 κρυμμένα επίπεδα και 1 επίπεδο εξόδου)**.


Χωρίστε τα training & test sets με αναλογία της επιλογής σας, αιτιολογώντας την με συντομία.

Για κάθε αρχιτεκτονική, θα πρέπει να εμφανίσετε σε πίνακες τα εξής αποτελέσματα:
- accuracy και recall (α) ανά κλάση και (β) συνολικά.
- confusion matrix.

Στο τέλος, σε ένα κελί κειμένου σχολιάστε σύντομα τα αποτελέσματα και συγκρίνετε τις δύο αρχιτεκτονικές για το συγκεκριμένο πρόβλημα.

Μπορείτε να χρησιμοποιήσετε όποιες βιβλιοθήκες, modules, κ.λπ. επιθυμείτε.

Για οποιοδήποτε βήμα δεν δίνεται συγκεκριμένη οδηγία (επιλογή παραμέτρων και υπερ-παραμέτρων, πλήθος νευρώνων σε κάθε επίπεδο, είδη στρωμάτων στο CNN, προεπεξεργασία δεδομένων, κ.λπ.) έχετε την ελευθερία επιλογής, παραθέτοντας μια σύντομη εξήγηση της επιλογής σας.

**Σε περιπτώσεις όπου εντοπίζεται αντιγραφή, η προσπάθεια θα μηδενίζεται.**

Θα πρέπει να ανεβάσετε το notebook σας στο helios στο σημείο που θα σας υποδειχθεί.

**Πριν το ανεβάσετε, βεβαιωθείτε ότι έχετε τρέξει όλα τα κελιά κώδικα που υπάρχουν στο notebook σας.**

Καλή επιτυχία!


In [ ]:
import numpy as np
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from sklearn.metrics import classification_report, confusion_matrix

The dataset has already been split into the train and test parts

In [ ]:
# Dataset Preparation
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

170498071/170498071 [==============================] - 5s 0us/step


In [ ]:
# Data Preprocessing
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [ ]:
# Convolutional Neural Network (CNN)
cnn_model = Sequential()
cnn_model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=x_train.shape[1:]))
cnn_model.add(Conv2D(32, (3, 3), activation='relu'))
cnn_model.add(MaxPooling2D(pool_size=(2, 2)))
cnn_model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
cnn_model.add(Conv2D(64, (3, 3), activation='relu'))
cnn_model.add(MaxPooling2D(pool_size=(2, 2)))
cnn_model.add(Flatten())
cnn_model.add(Dense(512, activation='relu'))
cnn_model.add(Dense(num_classes, activation='softmax'))

cnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
cnn_model.fit(x_train, y_train, batch_size=64, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
782/782 [==============================] - 289s 368ms/step - loss: 1.3818 - accuracy: 0.5012 - val_loss: 1.1143 - val_accuracy: 0.6129
Epoch 2/10
782/782 [==============================] - 282s 360ms/step - loss: 0.9355 - accuracy: 0.6707 - val_loss: 0.8693 - val_accuracy: 0.6971
Epoch 3/10
782/782 [==============================] - 314s 401ms/step - loss: 0.7249 - accuracy: 0.7455 - val_loss: 0.7960 - val_accuracy: 0.7236
Epoch 4/10
782/782 [==============================] - 278s 356ms/step - loss: 0.5790 - accuracy: 0.7993 - val_loss: 0.7839 - val_accuracy: 0.7286
Epoch 5/10
782/782 [==============================] - 284s 363ms/step - loss: 0.4400 - accuracy: 0.8461 - val_loss: 0.7624 - val_accuracy: 0.7563
Epoch 6/10
782/782 [==============================] - 284s 363ms/step - loss: 0.3206 - accuracy: 0.8872 - val_loss: 0.8616 - val_accuracy: 0.7487
Epoch 7/10
782/782 [==============================] - 288s 369ms/step - loss: 0.2218 - accuracy: 0.9237 - val_loss: 0.9809 -

In [ ]:
# Multilayer Perceptron (MLP)
mlp_model = Sequential()
mlp_model.add(Flatten(input_shape=x_train.shape[1:]))
mlp_model.add(Dense(256, activation='relu'))
mlp_model.add(Dense(128, activation='relu'))
mlp_model.add(Dense(64, activation='relu'))
mlp_model.add(Dense(32, activation='relu'))
mlp_model.add(Dense(num_classes, activation='softmax'))


mlp_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
mlp_model.fit(x_train, y_train, batch_size=64, epochs=50, validation_data=(x_test, y_test))

Epoch 1/50
782/782 [==============================] - 17s 20ms/step - loss: 1.9014 - accuracy: 0.3061 - val_loss: 1.7442 - val_accuracy: 0.3686
Epoch 2/50
782/782 [==============================] - 14s 18ms/step - loss: 1.7160 - accuracy: 0.3811 - val_loss: 1.6520 - val_accuracy: 0.4081
Epoch 3/50
782/782 [==============================] - 13s 17ms/step - loss: 1.6387 - accuracy: 0.4090 - val_loss: 1.6165 - val_accuracy: 0.4256
Epoch 4/50
782/782 [==============================] - 13s 17ms/step - loss: 1.5783 - accuracy: 0.4338 - val_loss: 1.5331 - val_accuracy: 0.4535
Epoch 5/50
782/782 [==============================] - 13s 17ms/step - loss: 1.5261 - accuracy: 0.4523 - val_loss: 1.5355 - val_accuracy: 0.4457
Epoch 6/50
782/782 [==============================] - 14s 17ms/step - loss: 1.5035 - accuracy: 0.4606 - val_loss: 1.5380 - val_accuracy: 0.4471
Epoch 7/50
782/782 [==============================] - 14s 18ms/step - loss: 1.4767 - accuracy: 0.4717 - val_loss: 1.5446 - val_accuracy:

In [ ]:
# Results Comparison
cnn_predictions = np.argmax(cnn_model.predict(x_test), axis=1)
mlp_predictions = np.argmax(mlp_model.predict(x_test), axis=1)

313/313 [==============================] - 1s 4ms/step


In [ ]:
# Calculate accuracy and recall per class
cnn_accuracy_per_class = np.mean(cnn_predictions == np.argmax(y_test, axis=1))
mlp_accuracy_per_class = np.mean(mlp_predictions == np.argmax(y_test, axis=1))

cnn_recall_per_class = classification_report(np.argmax(y_test, axis=1), cnn_predictions)
mlp_recall_per_class = classification_report(np.argmax(y_test, axis=1), mlp_predictions)

In [ ]:
# Calculate overall accuracy
cnn_accuracy_overall = np.mean(cnn_accuracy_per_class)
mlp_accuracy_overall = np.mean(mlp_accuracy_per_class)

In [ ]:
# Generate confusion matrix
cnn_confusion_matrix = confusion_matrix(np.argmax(y_test, axis=1), cnn_predictions)
mlp_confusion_matrix = confusion_matrix(np.argmax(y_test, axis=1), mlp_predictions)

In [ ]:
# Print the results
print("CNN Accuracy per class:", cnn_accuracy_per_class)
print("CNN Recall per class:\n", cnn_recall_per_class)
print("CNN Overall Accuracy:", cnn_accuracy_overall)
print("CNN Confusion Matrix:\n", cnn_confusion_matrix)

CNN Accuracy per class: 0.7364
CNN Recall per class:
               precision    recall  f1-score   support

           0       0.74      0.78      0.76      1000
           1       0.87      0.84      0.86      1000
           2       0.65      0.66      0.65      1000
           3       0.50      0.64      0.56      1000
           4       0.73      0.65      0.69      1000
           5       0.65      0.59      0.62      1000
           6       0.88      0.71      0.79      1000
           7       0.82      0.74      0.78      1000
           8       0.84      0.86      0.85      1000
           9       0.78      0.87      0.82      1000

    accuracy                           0.74     10000
   macro avg       0.75      0.74      0.74     10000
weighted avg       0.75      0.74      0.74     10000

CNN Overall Accuracy: 0.7364
CNN Confusion Matrix:
 [[782  17  52  16  10   5   7  10  60  41]
 [ 14 842   2   9   1   4   1   3  24 100]
 [ 70   6 661  79  65  45  26  24  13  11]
 [ 39 

In [ ]:
# Print the results
print("MLP Accuracy per class:", mlp_accuracy_per_class)
print("MLP Recall per class:\n", mlp_recall_per_class)
print("MLP Overall Accuracy:", mlp_accuracy_overall)
print("MLP Confusion Matrix:\n", mlp_confusion_matrix)

MLP Accuracy per class: 0.5063
MLP Recall per class:
               precision    recall  f1-score   support

           0       0.54      0.63      0.58      1000
           1       0.63      0.61      0.62      1000
           2       0.39      0.32      0.35      1000
           3       0.35      0.31      0.33      1000
           4       0.43      0.46      0.45      1000
           5       0.41      0.41      0.41      1000
           6       0.52      0.58      0.55      1000
           7       0.60      0.53      0.56      1000
           8       0.55      0.69      0.61      1000
           9       0.60      0.54      0.57      1000

    accuracy                           0.51     10000
   macro avg       0.50      0.51      0.50     10000
weighted avg       0.50      0.51      0.50     10000

MLP Overall Accuracy: 0.5063
MLP Confusion Matrix:
 [[633  36  39  19  30  22  16  24 140  41]
 [ 57 609  18  19   9  21  16  22  91 138]
 [ 96  16 317  96 153  85 111  66  45  15]
 [ 36 

Of course the CNN outperforms the MLP. The CNN does a decent job in distinguishing the 10 classes, while the MLP completely fails. It must be pointed out though, that the CNN had more neurons. While observing the training one can safely assume that the CNN actually learns the task, while the MLP just slightly improves in each epoch and possibly overfits. CNN's results in the test set can be greatly ameliorated by tweaking the number of neurons/layers and generally by performing hyperparameter tuning. The same case can't be made for MLP. These results were expected.